CREATE TABLE "PUBLIC"."APPLICATION"(
    "APPLICATION_ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(2000) NOT NULL,
    "APP_NAME" VARCHAR(255) NOT NULL,
    "OWNER" VARCHAR(255)
);

CREATE TABLE "PUBLIC"."TICKET"(
    "ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "STATUS" VARCHAR(255),
    "TITLE" VARCHAR(255),
    "APPLICATION_ID" BIGINT
);

CREATE TABLE "PUBLIC"."TICKET_RELEASE"(
    "RELEASE_FK" BIGINT,
    "TICKET_FK" BIGINT NOT NULL
);

CREATE TABLE "PUBLIC"."RELEASE"(
    "ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "RELEASE_DATE" VARCHAR(255) NOT NULL
);

CREATE TABLE "PUBLIC"."ROLES"(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(30)
);

CREATE TABLE "PUBLIC"."USER_ROLES"(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" INTEGER
);

CREATE TABLE "PUBLIC"."USERS"(
    "ID" BIGINT NOT NULL,
    "EMAIL" VARCHAR(50),
    "PASSWORD" VARCHAR(120),
    "USERNAME" VARCHAR(20)
);

create sequence "PUBLIC"."RELEASE_SEQ";
create sequence "PUBLIC"."TICKET_SEQ";
create sequence "PUBLIC"."SEQ";